### ISSUE TITLE
ValueDefinition support Debug

### ISSUE THREAD

**Issue by gilescope** [paritytech/scale-value#9]
It would be good to be able to display the structure of the type if debug formatted so that people can see how they might match against the structure.

**Comment by gilescope** [comment]
I.e. have a Debug implementation that shows whether things are a Composite or Named / Unnamed etc. so that from printout of one value you can see how you might construct a match statement several levels deep... for desub when it printed out the value it wasn't clear quite what the structure was if one wanted to match against it.

**Comment by jsdw** [comment]
Ah, I think I wrote debug impls for things in desub to make values more human readable, and then regretted that and ripped them all out in this crate, so things should already print in the way you're asking for I believe!

**Comment by jsdw** [comment]
Oh, actually I say that but there is one custom Debug impl on `ValueDef` that I missed, so I'll get rid of that too!
